### ISSUE TITLE
Source Category type is showing hydrofracturingindustrial, instead of industrieal

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/wateruse#17]
[Wateruseservices](https://test.streamstats.usgs.gov/docs/wateruseservices/#/Categories/GET/AllCategories) Seems fine, it seems the client is merging the options -> should be industrial. 

![image](https://user-images.githubusercontent.com/8713714/39997542-80381bdc-5740-11e8-97e5-92b6423a8fb7.png)

**Comment by kjacobsen16** [comment]
![image](https://user-images.githubusercontent.com/35497731/46492625-b98f4000-c7d3-11e8-8148-eb1fc28cb62d.png)
MA shows all category types

**Comment by kjacobsen16** [comment]
fixed
