### ISSUE TITLE
Remove ID from type

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/wateruse#18]
ID on column header not necessary. 
![image](https://user-images.githubusercontent.com/8713714/39997586-ad2cc2d2-5740-11e8-80c8-7df4123d0adf.png)

We could probably even set up the value to reference the code rather than Name as well, to keep it a bit more concise. ie. IN <-> industrial.... Thoughts???

**Comment by kjacobsen16** [comment]
done
